### ISSUE TITLE
No block styling when flush left, before any org heading

### ISSUE THREAD

**Issue by cpbotha** [jdtsmith/org-modern-indent#10]
Is it expected that blocks that are not indented, e.g. before the first section, don't show the block styling?

See the screenshot below for a demo.

The block styling will appear if I manually indent the block by a single space for example.

![image](https://github.com/jdtsmith/org-modern-indent/assets/937871/766089b6-27f9-46a5-b554-fe1da88a8808)

```org
Before any section

#+begin_src python
  def main():
      print("hello")
#+end_src

The following block is indented by a single space:

 #+begin_src python
   def main():
       print("hello")
 #+end_src

* dummy section

#+begin_src python
  def main():
      print("hello")
#+end_src

```

**Comment by jdtsmith** [comment]
Yes, this is expected, since flush-left blocks work by adding the styling to the indent space that org-indent adds.  There's no-where to put the styling!

**Comment by cpbotha** [comment]
Thank you for confirming that!

Would it in theory be possible to fall back to the same technique as base org-modern to handle only those cases where the block has 0 indent?

![image](https://github.com/jdtsmith/org-modern-indent/assets/937871/6eedfdda-88f4-417d-8379-c30d2b2afd88)

**Comment by jdtsmith** [comment]
In theory org-modern could, yes.  But blocks before any section seems to be a very rare case.

**Comment by cpbotha** [comment]
It was indeed rare for me too, until I started using org-roam a few years ago. Now my org database consists of a number of more traditional multi-heading org-files, and many more shorter, single-topic notes that have `#+TITLE:` fields, but no headings. :)

Thank you in any case very much for this great package!

I'll see how much my edge case encourages me to spend some hobby time at some point to see if I can coax `org-modern` into handling it.

**Comment by jdtsmith** [comment]
I see, good point.  Why not just use org-modern alone for that then?

**Comment by cpbotha** [comment]
As I mentioned, my database (the roam directory, which is everything) is a mix of single-topic and multiple-heading org-files.

**Comment by jdtsmith** [comment]
It may be easiest to coax org-modern to do its fringe-styling for any blocks prior to the first section, even when org-indent is enabled.   The other idea is to get org-indent to always add at least one space:

<img width="610" alt="image" src="https://github.com/jdtsmith/org-modern-indent/assets/93749/dabc56b8-bc69-412b-b5a0-12dcac947323">

**Comment by cpbotha** [comment]
Oh thank you, that's a great work-around!

I've added it to my config like this:

```lisp
;; the :vc is handled by https://github.com/slotThe/vc-use-package
(use-package org-modern-indent
  :vc (:fetcher github :repo jdtsmith/org-modern-indent)
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90)
  ;; https://github.com/jdtsmith/org-modern-indent/issues/10#issuecomment-1671726529
  (add-hook 'org-mode-hook (lambda() (aset org-indent--text-line-prefixes 0 (propertize " " 'face 'org-indent)))))
```
