### ISSUE TITLE
weird interaction between org-modern-indent and lsp-bridge?

### ISSUE THREAD

**Issue by nrvale0** [jdtsmith/org-modern-indent#12]
I don't know the exact source of the issue -- as in line of code -- but I've observed some strange behaviors from **org-modern-indent** after adding **lsp-bridge** to my config. Essentially, I see extra characters after an org-babel code block's **#+end_src**. (see attached screenshot).

![Screenshot from 2023-12-25 10-50-19](https://github.com/jdtsmith/org-modern-indent/assets/3616282/1bbba4ea-895a-427d-8b36-8423dd545181)

Here are the relevant config blocks for both **lsp-bridge** and **org-modern-indent**:

```
  (use-package org-modern-indent
    :elpaca (:host github :repo "jdtsmith/org-modern-indent")
    :init
    (setq org-startup-indented t)
    :config
    (add-hook 'org-mode-hook #'org-modern-indent-mode 90))
```

```
  (use-package lsp-bridge
    :after (markdown-mode yasnippet)
    :init (yas-global-mode 1)
    :elpaca '(lsp-bridge
	      :host github
	      :repo "manateelazycat/lsp-bridge"
	      :files (:defaults "*.el" "*.py" "acm/*.el" "core" "langserver" "multiserver" "resources")
	      :build (:not compile))
    :config
    (setq lsp-bridge-enable-org-babel t)
    (global-lsp-bridge-mode))
```

Toggling **org-modern-indent** (obviously) removes the extra characters (and all other indent emphasis) however toggling **lsp-bridge** off does not restore normal behavior. Based on that, its perhaps possible that attributing the behavior to an interaction with **lsp-bridge** is a red herring.

Much appreciated.

**Comment by jdtsmith** [comment]
I doubt lsp-bridge has anything to do with it.  Can you provide a simple recipe to reproduce from emacs -Q?  What do you do to get the extra characters to appear?  BTW, you seem to be suffering from gaps; see note on  [font spacing](https://github.com/jdtsmith/org-modern-indent#font-spacing).

**Comment by jdtsmith** [comment]
What wrap mode do you have enabled?  Can you disable `visual-line-mode` and enable truncate-mode and see if that changes anything?  The last line, when wrapped, draws another end bracket.  So perhaps you have a ton of spaces after `end_src`?
