### ISSUE TITLE
user-error "org-modern-indent: Gave up waiting for x.org to initialize

### ISSUE THREAD

**Issue by ParetoOptimalDev** [jdtsmith/org-modern-indent#16]
For every file in `~/org` I get this error when using org-ql-view. Reproduce with:

`/tmp/org/foo.org`:

```
* TODO foo
* TODO bar
```

`/tmp/org/bar.org`:

```
* TODO foo
* TODO bar
```

```emacs-lisp
(let ((org-agenda-files '("/tmp/org/bar.org" "/tmp/org/foo.org"))) (org-ql-search (org-agenda-files) '(todo)))
```

Using config:

```emacs-lisp
(use-package org
  :init
  (defun my/org-mode-setup ()
    ;; Make sure org-indent face is available
    (require 'org-indent)
    (org-indent-mode 1)
    (variable-pitch-mode 1)
    )
  :hook
  (org-mode . my/org-mode-setup))
(use-package org-modern-indent
  :config
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90))
```

I get error:

```
Error running timer ‘org-modern-indent--wait-and-refresh’: (user-error "org-modern-indent: Gave up waiting for bar.org to initialize")
```
So it fails for the first one I guess?

I'm using `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll bars)`.

Let me know if you need any more information.

**Comment by jdtsmith** [comment]
See also #11, where we installed that user-error.  This is a temporary situation while we wait for org 9.7, which will have an appropriate callback hook when it finalizes a given buffer.
