### ISSUE TITLE
Error "Selecting deleted buffer" when creating org-roam nodes

### ISSUE THREAD

**Issue by rdiaz02** [jdtsmith/org-modern-indent#17]
When I try to create a new org-roam node (using òrg-roam-node-find`), I get a 

```
Error running timer ‘org-modern-indent--wait-and-refresh’: (error "Selecting deleted buffer")
```

The backtrace is

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
org-modern-indent--wait-and-refresh(#<killed buffer>)
apply(org-modern-indent--wait-and-refresh #<killed buffer>)
timer-event-handler([t 26107 13931 933744 nil org-modern-indent--wait-and-refresh (#<killed buffer>) nil 716000 nil])
```

This can be reproduced as follows

1. emacs -Q
2. Eval the following code (change the directory wherever you want; it does not need to have any files)
```elisp
(package-initialize)

(setq org-startup-indented t)
(require 'org)
(require 'org-modern)
(require 'org-indent)
(use-package org-modern-indent
  :load-path "/home/ramon/Sources/emacs-packages/org-modern-indent/"
  :commands (org-modern-indent-mode)
  :init
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90)
  )
(with-eval-after-load 'org (global-org-modern-mode))

(setq org-roam-directory (file-truename "~/tmp/tmp2"))

(org-roam-node-find)

```
3. Type anything for the name when prompted, press enter.
4. Error

5. Interestingly, though, nodes can be created just fine. The problem seems limited to the annoying error message.

This seems the same problem as reported in https://github.com/jdtsmith/org-modern-indent/issues/6#issuecomment-1987474010  .  I am opening a new issue since this seems a separate problem from the original one in that issue. Note, also, that this is not dependent on any specific capture templates (I specified none above).

**Comment by jdtsmith** [comment]
These are all related issues which will be solved when Org 9.7 is released.  I tried to guard against this specific error in a4d2429.  Can you test latest master and let me know if that fixes it?

**Comment by jdtsmith** [comment]
I don't understand: the buffer is deleted, right?  I'm not sure how you are viewing a deleted buffer here.  Can you clarify?

**Comment by rdiaz02** [comment]
So I do the `(org-roam-node-find)`. That creates some kind of termporary buffer; I add a quote, but I have not yet created the note for real:
![capturing](https://github.com/jdtsmith/org-modern-indent/assets/1688611/0db2bc30-fca9-46b9-821a-a933c7ed7c5a)

I do 'C-c C-c`: now, the org-roam buffer changes its name and there is an associated file, as can be seen by the name change.  But still no vertical lines in the quote
![just-capured](https://github.com/jdtsmith/org-modern-indent/assets/1688611/976c86e6-a0f2-4975-8d68-221d804e40e9)

After revert buffer we get the vertical aline in the quote block:
![after-revert-buffer](https://github.com/jdtsmith/org-modern-indent/assets/1688611/979789be-9b45-4c6b-b8c8-4102d67fbdf9)


I am not sure I fully understand your question. But In the first screen capture I am seeing the CAPTURE buffer. In the second, that buffer is already associated with a file in the org-roam directory. That is the same one shown in the third figure, the only difference being that I did `revert-buffer`.

**Comment by jdtsmith** [comment]
You can see that the error is "selecting deleted buffer".  That makes sense for the buffer `CAPTURE-XXX.org`; it is getting deleted before `org-indent` gets around to indenting it, so it's correct for `org-modern-indent` to ignore it.  But why is the associated `XXXX.org` not getting added to the list?

I've merged my branch which uses the new org-indent hook; you could try upgrading to an Org v9.7 pre-release. Give it a test either way (likely same behavior for you).

**Comment by jdtsmith** [comment]
I think this is org-capture's fault.  It's doing some crazy things with buffers, but org-indent knows about and handles this, so we need to defer to it, possible once org 9.7 drops (soon I hope).

**Comment by rdiaz02** [comment]
> You can see that the error is "selecting deleted buffer". That makes sense for the buffer `CAPTURE-XXX.org`; it is getting deleted before `org-indent` gets around to indenting it, so it's correct for `org-modern-indent` to ignore it. But why is the associated `XXXX.org` not getting added to the list?
 
I cannot tell why it is not getting added to the list (I assume you mean the list of buffers to be affected by org-modern-indent?). I think the buffer gets renamed and then saved to a file? But I really have no idea what is happening: crazy stuff.  :-)

As I say, if I  `revert-buffer`  or if I later open that file (from another emacs session, for example) things work as expected. So the "not properly formatted" seems to last only until the first revisiting of the file. Not a big deal either.

> I've merged my branch which uses the new org-indent hook; you could try upgrading to an Org v9.7 pre-release. Give it a test either way (likely same behavior for you).
> I think this is org-capture's fault. It's doing some crazy things with buffers, but org-indent knows about and handles this, so we need to defer to it, possible once org 9.7 drops (soon I hope).

I think I'll wait until 9.7 is release (too much stuff right now to update to org 9.7 pre-release). 

Thanks again!
