### ISSUE TITLE
block styling with different startup visibilities

### ISSUE THREAD

**Issue by Dickby** [jdtsmith/org-modern-indent#2]
I normally have my org-mode config to `#+startup overview`.
My init.org file has a few hundred headings, only the upper code-blocks get styled by org-modern-inent.
If i use `#+startup all` it works fine for all code blocks.
Nice package by the way
Thanks

**Comment by jdtsmith** [comment]
Not sure what you mean by upper code-blocks?   Do you mean they start folded and look like this?  
![image](https://user-images.githubusercontent.com/93749/173629569-60077cad-d537-41c4-8dbc-40b807a21ba3.png)

**Comment by Dickby** [comment]
With upper blocks, i meant that the first (maybe 50 or so) blocks get styled the ones after that not.

**Comment by Dickby** [comment]
It's actually much less than 50.

**Comment by jdtsmith** [comment]
I just tried on an example file with 6000 blocks and didn't encounter issues.  I do get the message "Setting buffer indentation.  It may take a few seconds..." from org-indent.

**Comment by Dickby** [comment]
I will try it without any other packages enabled to see if it's my configuration.

**Comment by Dickby** [comment]
It doesn't happen if i only load org-modern-indent and no other packages.
I'm trying to hunt the reason down, but it's not that easy.
I'll let you know when i find it.

**Comment by jdtsmith** [comment]
I'll close this for now, but please report back when you learn the offending setting/package, in case someone else has the same issue.

**Comment by sincebyte** [comment]
> Not sure what you mean by upper code-blocks? Do you mean they start folded and look like this? ![image](https://user-images.githubusercontent.com/93749/173629569-60077cad-d537-41c4-8dbc-40b807a21ba3.png).
> 
> `#+STARTUP: overview` works fine here; blocks get styled as they get indented by org-indent, as they are revealed.

I'm wonder there have a solution or not? and how.

**Comment by jdtsmith** [comment]
Solution to what?

**Comment by sincebyte** [comment]
> Solution to what?
When code block folded, there display `┌SRC yaml ...`
whereas the expected is a other sign of org-modern-indent-begin when code block havs been folded.
some thing like `☰SRC yaml ...`

**Comment by jdtsmith** [comment]
The package does not do folding at all.  I'll keep it in mind.
