### ISSUE TITLE
Loading org-modern-indent problem

### ISSUE THREAD

**Issue by mclearc** [jdtsmith/org-modern-indent#3]
Thanks for this package. I'm seeing a weird problem with loading org-modern-indent via the suggested hook. I keep getting an `org-indent-add-properties: Wrong type argument: arrayp, nil` error. 

If I load it not by the hook but by calling the command manually after opening an org buffer though there is no problem. My setup is below -- any ideas are appreciated. 

```emacs-lisp
(setq org-startup-indented t) 

;;;; Org Modern Indent
;; Make org-modern work better with org-indent
(use-package org-modern-indent
  :straight (:type git :host github :repo "jdtsmith/org-modern-indent")
  :hook (org-mode . org-modern-indent-mode))
```
Note that I see no difference in the problem whether or not org-modern is loaded. Here also is a debug report:

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  org-indent-set-line-properties(1 0 t)
  org-indent-add-properties(1 556)
  org-indent-indent-buffer()
  org-modern-indent-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  funcall-interactively(org-mode)
  command-execute(org-mode record)
  execute-extended-command(nil "org-mode" nil)
  funcall-interactively(execute-extended-command nil "org-mode" nil)
  command-execute(execute-extended-command)
```

**Comment by jdtsmith** [comment]
Probably I should hook to `org-indent-mode` instead.  Can you try that and let me know?

**Comment by mclearc** [comment]
Thanks -- I actually thought I had tried this but apparently not because it works! So might be worth updating the docs. But great package!

**Comment by jdtsmith** [comment]
Thanks, done.
