### ISSUE TITLE
Elfeed display issue (v0.1)

### ISSUE THREAD

**Issue by rnadler** [jdtsmith/org-modern-indent#7]
I installed v0.1 and found that the font faces used in the elfeed **\*elfeed-search\*** buffer get wiped out.  You can see the initial elfeed draw with the correct faces and then something redraws the buffer immediately after. Subsequent elfeed face changes (read, star, etc.) also do not work.

**Comment by jdtsmith** [comment]
Hmm, this sounds like an issue with the font-locker settings escaping.  In your elfeed buffer when this happens, can you `C-h v [Ret] font-lock-keywords [Ret]` and look for `org-modern-indent--block-bracket`?

**Comment by jdtsmith** [comment]
I have introduced a defensive fix to guard against this "escape".  Can you try it out and let me know?

**Comment by rnadler** [comment]
@jdtsmith The fix resolved the issue. Thanks!
