### ISSUE TITLE
custom-set-faces break org-indent ?

### ISSUE THREAD

**Issue by Cletip** [jdtsmith/org-modern-indent#9]
If I am right, I think that this two commands do the same things :

```
(set-face-attribute 'fixed-pitch t :family "Ubuntu mono" :height 1.0)

(custom-set-faces '(fixed-pitch ((t (:family "Ubuntu mono" :height 1.0)))))
```

But, custom-set-faces break org-indent like this :

![Capture d’écran du 2023-05-18 21-00-01](https://github.com/jdtsmith/org-modern-indent/assets/81437869/0fe3123d-5987-4e75-bbb5-d296a7895a0c)

**Comment by jdtsmith** [comment]
Not really sure what you are trying to accomplish here.  I doubt the manner of setting a face attribute could cause any such change.  What is the actual problem you are experiencing?

**Comment by Cletip** [comment]
I just tried to change the "fixed-pitch" face in two different ways (listed above). But one of them causes a misalignment in org-modern-indent (as you can see in the screenshot). I don't understand why because these two commands are supposed to do the same thing. Can you reproduce this issue?

**Comment by jdtsmith** [comment]
My guess is one of them is malformed but I am not sure as I don't use these commands.  There doesn't seem to be a problem here though if you use the one that works.
